### PR TITLE
Used urllib2 instead of socket

### PR DESCRIPTION
**Pull request by miheerdew**
This is a fix for hathway redirecting http connections. We make https connnections. However urlopen doesn't verify the certificate (which we should to ensure that we have successfully made a connection with google).  

I still haven't checked this. Will let you know if it works.

### CODE REVIEW

**Comment by sameer-b** [comment]
After you test it we will merge into master.

**Comment by miheerdew** [comment]
I doesn't work properly. I will not be on the hathway network till December, so I guess this will have to wait.

**Comment by rickysarraf** [comment]
I don't think this one needs to be merged.

**Comment by miheerdew** [comment]
Hmm, so when you type www.google.com in your browser, the hathway does not redirect you to its login site ( or some other page which shows a cannot be reached message )?

**Comment by sameer-b** [comment]
closing this pull request. switching to rick'ys branch. he has been using it and it works.

**Pull request closed without merging**
